function Get-CompatibleID {
    [CmdLetBinding()]
    [Outputtype([string])]
    param(
        [Parameter(Mandatory,ValueFromPipeline,ValueFromPipelineByPropertyName)]
        [ValidateNotNullOrEmpty()]
        [string]$HardwareID
    )

    process {
        $Identifier = $HardwareID.Split('\')
        $Bus = $Identifier[0]
        if ($Bus -eq 'PCI') {
            # PCI devices
            # Taken from https://docs.microsoft.com/en-us/windows-hardware/drivers/install/identifiers-for-pci-devices
            # Standard Formats for PCI Devices.
            # PCI\VEN_v(4)&DEV_d(4)&SUBSYS_s(4)n(4)&REV_r(2)
            # PCI\VEN_v(4)&DEV_d(4)&SUBSYS_s(4)n(4)
            # PCI\VEN_v(4)&DEV_d(4)&REV_r(2)
            # PCI\VEN_v(4)&DEV_d(4)
            #
            # Compatible formats generated by the PCI bus driver
            # PCI\VEN_v(4)&DEV_d(4)&REV_r(2)
            # PCI\VEN_v(4)&DEV_d(4)
            #
            # Generate list of compatible formats based on above

            # Try to identify components
            $Components = $Identifier[1].Split('&')
            foreach ($Component In $Components) {
                if ($Component -like 'VEN_*') {
                    $Vendor = $Component
                } elseif ($Component -like 'DEV_*') {
                    $Device = $Component
                } elseif ($Component -like 'SUBSYS_*') {
                    $Subsystem = $Component
                } elseif ($Component -like 'REV_*') {
                    $Revision = $Component
                } elseif ($Component -like 'CC_*') {
                    $ClassCode = $Component
                } else {
                    Write-Verbose "Unable to identify Device component '$Component' from HardwareID '$HardwareID'."
                }
            }

            if (-Not([string]::IsNullOrEmpty($Vendor))) {
                if (-Not([string]::IsNullOrEmpty($Device))) {
                    "PCI\$Vendor&$Device"
                    if (-Not([string]::IsNullOrEmpty($Revision))) {
                        "PCI\$Vendor&$Device&$Revision"
                        # if (-Not([string]::IsNullOrEmpty($Subsystem))) {
                        #     "PCI\$Vendor&$Device&$Subsystem&$Revision"
                        # }
                    }
                    if (-Not([string]::IsNullOrEmpty($Subsystem))) {
                        "PCI\$Vendor&$Device&$Subsystem"
                    }
                }
            }

        } elseif ($Bus -eq 'PCI') {
            # Standard USB Identifiers - https://docs.microsoft.com/en-us/windows-hardware/drivers/install/standard-usb-identifiers
            # Single interface devices
            # USB\VID_v(4)&PID_d(4)&REV_r(4)
            #
            # USB\VID_v(4)&PID_d(4)
            # USB\CLASS_c(2)&SUBCLASS_s(2)&PROT_p(2)
            # USB\CLASS_c(2)&SUBCLASS_s(2)
            # USB\CLASS_c(2)
            #
            # Multi interface devices
            # USB\VID_v(4)&PID_d(4)&MI_z(2)#
            # USB\CLASS_d(2)&SUBCLASS_s(2)&PROT_p(2)
            # USB\CLASS_d(2)&SUBCLASS_s(2)
            # USB\CLASS_d(2)
            # USB\COMPOSITE
            #
            # Try to identify components
            $Components = $Identifier[1].Split('&')
            foreach ($Component In $Components) {
                if ($Component -like 'VID_*') {
                    $Vendor = $Component
                } elseif ($Component -like 'PID_*') {
                    $Product = $Component
                } elseif ($Component -like 'REV_*') {
                    $Revision = $Component
                } elseif ($Component -like 'MI_*') {
                    $Interface = $Component
                } else {
                    Write-Verbose "Unable to identify Device component '$Component' from HardwareID '$HardwareID'."
                }
            }

            if (-Not([string]::IsNullOrEmpty($Vendor))) {
                if (-Not([string]::IsNullOrEmpty($Product))) {
                    "USB\$Vendor&$Product"
                }
            }
        } else {
            # $HardwareID
        }

        #Always return the input object
        $HardwareID
    }
}